#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PathButton.Resource", IsApplication=true)]

namespace PathButton
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::PathbuttonLib.Resource.Animation.sat_item_anim_click = global::PathButton.Resource.Animation.sat_item_anim_click;
			global::PathbuttonLib.Resource.Animation.sat_item_anticipate_interpolator = global::PathButton.Resource.Animation.sat_item_anticipate_interpolator;
			global::PathbuttonLib.Resource.Animation.sat_item_click_interpolator = global::PathButton.Resource.Animation.sat_item_click_interpolator;
			global::PathbuttonLib.Resource.Animation.sat_item_in_rotate_interpolator = global::PathButton.Resource.Animation.sat_item_in_rotate_interpolator;
			global::PathbuttonLib.Resource.Animation.sat_item_out_rotate_interpolator = global::PathButton.Resource.Animation.sat_item_out_rotate_interpolator;
			global::PathbuttonLib.Resource.Animation.sat_item_overshoot_interpolator = global::PathButton.Resource.Animation.sat_item_overshoot_interpolator;
			global::PathbuttonLib.Resource.Animation.sat_main_rotate_left = global::PathButton.Resource.Animation.sat_main_rotate_left;
			global::PathbuttonLib.Resource.Animation.sat_main_rotate_right = global::PathButton.Resource.Animation.sat_main_rotate_right;
			global::PathbuttonLib.Resource.Attribute.closeOnClick = global::PathButton.Resource.Attribute.closeOnClick;
			global::PathbuttonLib.Resource.Attribute.expandDuration = global::PathButton.Resource.Attribute.expandDuration;
			global::PathbuttonLib.Resource.Attribute.mainImage = global::PathButton.Resource.Attribute.mainImage;
			global::PathbuttonLib.Resource.Attribute.satelliteDistance = global::PathButton.Resource.Attribute.satelliteDistance;
			global::PathbuttonLib.Resource.Attribute.totalSpacingDegree = global::PathButton.Resource.Attribute.totalSpacingDegree;
			global::PathbuttonLib.Resource.Drawable.sat_item = global::PathButton.Resource.Drawable.sat_item;
			global::PathbuttonLib.Resource.Drawable.sat_main = global::PathButton.Resource.Drawable.sat_main;
			global::PathbuttonLib.Resource.Id.sat_item = global::PathButton.Resource.Id.sat_item;
			global::PathbuttonLib.Resource.Id.sat_main = global::PathButton.Resource.Id.sat_main;
			global::PathbuttonLib.Resource.Layout.sat_item_cr = global::PathButton.Resource.Layout.sat_item_cr;
			global::PathbuttonLib.Resource.Layout.sat_main = global::PathButton.Resource.Layout.sat_main;
			global::PathbuttonLib.Resource.String.empty = global::PathButton.Resource.String.empty;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu = global::PathButton.Resource.Styleable.SatelliteMenu;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu_closeOnClick = global::PathButton.Resource.Styleable.SatelliteMenu_closeOnClick;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu_expandDuration = global::PathButton.Resource.Styleable.SatelliteMenu_expandDuration;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu_mainImage = global::PathButton.Resource.Styleable.SatelliteMenu_mainImage;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu_satelliteDistance = global::PathButton.Resource.Styleable.SatelliteMenu_satelliteDistance;
			global::PathbuttonLib.Resource.Styleable.SatelliteMenu_totalSpacingDegree = global::PathButton.Resource.Styleable.SatelliteMenu_totalSpacingDegree;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int sat_item_anim_click = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int sat_item_anticipate_interpolator = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int sat_item_click_interpolator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int sat_item_in_rotate_interpolator = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int sat_item_out_rotate_interpolator = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int sat_item_overshoot_interpolator = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int sat_main_rotate_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int sat_main_rotate_right = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int closeOnClick = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int expandDuration = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int mainImage = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int satelliteDistance = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int totalSpacingDegree = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_3 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_4 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_5 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_6 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int main = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sat_item = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sat_main = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int menu = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int sat_item = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int sat_main = 2131099650;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int sat_item_cr = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int sat_main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int empty = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SatelliteMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int SatelliteMenu_closeOnClick = 1;
			
			// aapt resource value: 0
			public const int SatelliteMenu_expandDuration = 0;
			
			// aapt resource value: 4
			public const int SatelliteMenu_mainImage = 4;
			
			// aapt resource value: 3
			public const int SatelliteMenu_satelliteDistance = 3;
			
			// aapt resource value: 2
			public const int SatelliteMenu_totalSpacingDegree = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
