#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PathbuttonLib.Resource", IsApplication=false)]

namespace PathbuttonLib
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public static int sat_item_anim_click = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int sat_item_anticipate_interpolator = 2130968577;
			
			// aapt resource value: 0x7f040002
			public static int sat_item_click_interpolator = 2130968578;
			
			// aapt resource value: 0x7f040003
			public static int sat_item_in_rotate_interpolator = 2130968579;
			
			// aapt resource value: 0x7f040004
			public static int sat_item_out_rotate_interpolator = 2130968580;
			
			// aapt resource value: 0x7f040005
			public static int sat_item_overshoot_interpolator = 2130968581;
			
			// aapt resource value: 0x7f040006
			public static int sat_main_rotate_left = 2130968582;
			
			// aapt resource value: 0x7f040007
			public static int sat_main_rotate_right = 2130968583;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int closeOnClick = 2130771969;
			
			// aapt resource value: 0x7f010000
			public static int expandDuration = 2130771968;
			
			// aapt resource value: 0x7f010004
			public static int mainImage = 2130771972;
			
			// aapt resource value: 0x7f010003
			public static int satelliteDistance = 2130771971;
			
			// aapt resource value: 0x7f010002
			public static int totalSpacingDegree = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int sat_item = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int sat_main = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public static int sat_item = 2131099648;
			
			// aapt resource value: 0x7f060001
			public static int sat_main = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public static int sat_item_cr = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int sat_main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int empty = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SatelliteMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public static int SatelliteMenu_closeOnClick = 1;
			
			// aapt resource value: 0
			public static int SatelliteMenu_expandDuration = 0;
			
			// aapt resource value: 4
			public static int SatelliteMenu_mainImage = 4;
			
			// aapt resource value: 3
			public static int SatelliteMenu_satelliteDistance = 3;
			
			// aapt resource value: 2
			public static int SatelliteMenu_totalSpacingDegree = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
